import { defineConfig } from '@umijs/max'

export default defineConfig({
  antd: {
    theme: {
      token: {
        colorPrimary: '#13a8a8',
        colorInfo: '#1677ff',
        colorSuccess: '#52c41a',
        colorWarning: '#faad14',
        colorError: '#ff4d4f',
        colorBgLayout: '#f4fbfb',
        colorBgContainer: '#ffffff',
        colorBgElevated: '#ffffff',
        colorFillAlter: '#f0f9f9',
        colorBorderSecondary: '#d8eeee',
        fontSize: 13,
        fontSizeLG: 14,
        fontSizeSM: 12,
        borderRadius: 10,
        borderRadiusLG: 14,
        borderRadiusSM: 6,
        controlHeight: 32,
        controlHeightLG: 38,
        controlHeightSM: 26,
        padding: 14,
        paddingLG: 20,
        paddingMD: 14,
        paddingSM: 10,
        margin: 14,
        marginLG: 20,
        marginMD: 14,
        marginSM: 10,
        wireframe: false,
      },
      components: {
        Button: {
          borderRadius: 8,
          controlHeight: 32,
          controlHeightLG: 38,
          controlHeightSM: 26,
          primaryShadow: '0 6px 14px rgba(19, 168, 168, 0.16)',
        },
        Card: {
          borderRadiusLG: 14,
          paddingLG: 18,
          boxShadowTertiary: '0 10px 30px rgba(15, 77, 82, 0.06)',
        },
        Table: {
          headerBg: '#f2fbfb',
          headerColor: '#24474a',
          headerSplitColor: '#d8eeee',
          rowHoverBg: '#eefafa',
          borderColor: '#e2f1f1',
          cellPaddingBlock: 10,
          cellPaddingInline: 12,
          cellPaddingBlockMD: 8,
          cellPaddingInlineMD: 10,
          cellFontSize: 13,
          headerBorderRadius: 10,
        },
        Layout: {
          bodyBg: '#f4fbfb',
          headerBg: '#ffffff',
          siderBg: '#ffffff',
          triggerBg: '#f0f9f9',
        },
        Menu: {
          itemBorderRadius: 8,
          itemHeight: 38,
          itemMarginBlock: 3,
          itemMarginInline: 8,
          fontSize: 13,
          itemSelectedBg: '#d9f5f5',
          itemSelectedColor: '#0f8b8d',
          itemHoverBg: '#e6fafa',
          itemHoverColor: '#0f8b8d',
          itemColor: '#176b6d',
        },
        Modal: {
          borderRadiusLG: 14,
          contentBg: '#ffffff',
          headerBg: '#ffffff',
        },
        Tag: {
          borderRadiusSM: 999,
        },
      },
    },
  },
  access: {},
  model: {},
  initialState: {},
  request: {},
  layout: {
    title: '医护自学资源后台',
    locale: false,
    layout: 'mix',
    contentWidth: 'Fluid',
    fixedHeader: true,
    fixSiderbar: true,
    splitMenus: false,
    siderWidth: 224,
    colorWeak: false,
  },
  routes: [
    { path: '/', redirect: '/subjects' },
    { path: '/dashboard', redirect: '/nursing/dashboard' },
    {
      path: '/subjects',
      name: '学科工作台',
      icon: 'AppstoreOutlined',
      component: './SubjectWorkspace',
    },
    {
      path: '/nursing/dashboard',
      name: '医护工作台',
      icon: 'DashboardOutlined',
      component: './Dashboard',
    },
    {
      path: '/nursing/students',
      name: '学生信息管理',
      icon: 'TeamOutlined',
      component: './Students',
    },
    {
      path: '/nursing/license-tokens',
      name: '授权码台账',
      icon: 'SafetyCertificateOutlined',
      component: './LicenseTokens',
    },
    {
      path: '/nursing/problems',
      name: '四模块题库管理',
      icon: 'FileTextOutlined',
      routes: [
        { path: '/nursing/problems', redirect: '/nursing/problems/list' },
        { path: '/nursing/problems/list', name: '题目列表', component: './Problems' },
        { path: '/nursing/problems/import', name: '题目导入', component: './ProblemImport' },
        { path: '/nursing/problems/drafts', name: '草稿清洗池', component: './ProblemDrafts' },
      ],
    },
    {
      path: '/nursing/video-lessons',
      name: '四模块视频分发',
      icon: 'PlaySquareOutlined',
      component: './VideoLessons',
    },
    {
      path: '/nursing/assets',
      name: '素材上传与预览',
      icon: 'CloudUploadOutlined',
      component: './Assets',
    },
    {
      path: '/nursing/knowledge-points',
      name: '知识点管理（预留）',
      hideInMenu: true,
      icon: 'ApartmentOutlined',
      component: './KnowledgePoints',
    },
    {
      path: '/nursing/case-materials',
      name: '案例材料（预留）',
      hideInMenu: true,
      icon: 'ReadOutlined',
      component: './CaseMaterials',
    },
    {
      path: '/nursing/confusing-points',
      name: '易混点（预留）',
      hideInMenu: true,
      icon: 'SwapOutlined',
      component: './ConfusingPoints',
    },
    {
      path: '/nursing/memory-tips',
      name: '记忆提示（预留）',
      hideInMenu: true,
      icon: 'BulbOutlined',
      component: './MemoryTips',
    },
    {
      path: '/nursing/daily-problems',
      name: '每日练习（预留）',
      hideInMenu: true,
      icon: 'CalendarOutlined',
      component: './DailyProblems',
    },
    {
      path: '/nursing/reviews',
      name: '发布审核（预留）',
      hideInMenu: true,
      icon: 'SafetyCertificateOutlined',
      component: './Reviews',
    },
    {
      path: '/math',
      name: '高数入口',
      icon: 'FunctionOutlined',
      component: './MathHolding',
    },
  ],
  npmClient: 'pnpm',
})
