export default defineAppConfig({
  __usePrivacyCheck__: true,
  pages: [
    'pages/practice/index',
    'pages/question-bank/index',
    'pages/study-cards/index',
    'pages/exam/index',
    'pages/profile/index',
    'pages/activate/index',
    'pages/sync-profile/index',
    'pages/question-detail/index',
    'pages/question-bank-module/index',
    'pages/study-card-list/index',
    'pages/study-card-detail/index',
    'pages/study-card-point/index',
    'pages/exam-session/index',
    'pages/exam-result/index',
    'pages/ranking/index',
    'pages/settings/index',
    'pages/learning-report/index',
  ],
  tabBar: {
    color: '#a8a29e',
    selectedColor: '#38c9a0',
    backgroundColor: '#ffffff',
    borderStyle: 'white',
    list: [
      { pagePath: 'pages/practice/index', text: '练习' },
      { pagePath: 'pages/question-bank/index', text: '题库' },
      { pagePath: 'pages/study-cards/index', text: '带背' },
      { pagePath: 'pages/exam/index', text: '模考' },
      { pagePath: 'pages/profile/index', text: '我的' },
    ],
  },
  window: {
    backgroundTextStyle: 'dark',
    navigationBarBackgroundColor: '#ecfdf5',
    navigationBarTitleText: '医护自学辅助',
    navigationBarTextStyle: 'black',
    backgroundColor: '#f6fcfa',
  },
})
